### ISSUE TITLE
refresh controller sends back an error

### ISSUE THREAD

**Issue by faridhashimov** [faridhashimov/ecommerce-store#1]
refresh controller sends back an error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

**Comment by ujwalkumar1995** [comment]
Hi @faridhashimov 
I would like to give this issue a try.
Could you please help me replicate the issue. For instance user flow where this bug occurs.

**Comment by faridhashimov** [comment]
Hi @ujwalkumar1995
This bug occurs when user try to fetch his orders in his profile, which needs fresh access token. Becasuse of our token expires after 5s from login,  we send refresh request from our rtk query api. But because of bug in auth controller it can't send refresh token back.

**Comment by ujwalkumar1995** [comment]
Hey @faridhashimov 
The login credentials were not working. Are there any migrations that need to be run in order to populate the database?
I can only see data in clients and projects table.
Anyways, I tried to register my own user locally and was able to do so. But it is failing after the login screen with some error.
I am trying to look into that.
I have also found couple of other minor bugs. Do you mind if I create bug issues for those as well so someone can pick those up?

**Comment by faridhashimov** [comment]
@ujwalkumar1995 I don't mind.

**Comment by faridhashimov** [comment]
Hey @ujwalkumar1995 I just realizes that i didn't push last changes to github. Did it already, please fetch last changes.

**Comment by ujwalkumar1995** [comment]
Hey @faridhashimov 
Took the latest pull. Still unable to login. I am able to traverse through rest of the website but login does not work.

**Comment by faridhashimov** [comment]
Hey @ujwalkumar1995, try to change `baseUrl ` to https://ecommerce-store-backend.vercel.app/api/ in redux/ecommerceApi file

**Comment by ujwalkumar1995** [comment]
Hi @faridhashimov 
I don't think changing the baseUrl would be much helpful here as I need to run the backend locally in order to debug. Anyways, I was able to somehow run the application locally. 
I have few observations but unfortunately I am finding it hard to come with a working solution.

![Screenshot_20230222_122720](https://user-images.githubusercontent.com/20976813/220434972-65a0943c-cbf4-4d18-83e7-1cb4714948ea.png)
After the method call at line 20, it calls the below method. 
![Screenshot_20230222_122702](https://user-images.githubusercontent.com/20976813/220439226-94534382-c8bc-47e2-be3a-7b8999aa4d1c.png)
As the token is expired it sets the status as 403 and returns the response to the client. After the response has been returned to the client, it is unable to update the headers on the client with your refresh token as we can only send 1 response for 1 request and after that we cannot make updates on it.

**Comment by faridhashimov** [comment]
> @ujwalkumar1995 actually yoe are right, by adding return before `res.status(403)` I think we can solve the issue with refresh token

**Comment by ujwalkumar1995** [comment]
Hey @faridhashimov 
I tried this solution earlier. Although the backend does not crash after adding this. But still in the console I see below error. So don't think this is working as expected.
![Screenshot_20230222_083705](https://user-images.githubusercontent.com/20976813/220664229-6ec99969-a05a-4744-9df8-97047ab91097.png)

**Comment by faridhashimov** [comment]
hey @ujwalkumar1995, It's beacuse access token expires and we immediately get back error, and send request with refresh token. I think we fixed main bug.

**Comment by ujwalkumar1995** [comment]
Hey @faridhashimov 
If you think adding return fixes the problem, do you want me to raise a PR with the fix?

**Comment by faridhashimov** [comment]
@ujwalkumar1995  I've already fixed bug, and pushed it main branch.
